// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXr6lG2ZVQxVci_Ne_K7snjATk6ImCIhM',
    appId: '1:735764021781:android:b2af34d5e6c6974cc7441c',
    messagingSenderId: '735764021781',
    projectId: 'firstapp-3645c',
    storageBucket: 'firstapp-3645c.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqcpIYNXex4t6nO1rpND92ksaRdtt_8l4',
    appId: '1:735764021781:web:69d5a6d7e1d4ccdbc7441c',
    messagingSenderId: '735764021781',
    projectId: 'firstapp-3645c',
    authDomain: 'firstapp-3645c.firebaseapp.com',
    storageBucket: 'firstapp-3645c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAx4JcY3RVoHk_KC5VpBmNCMv2KHvSNqA',
    appId: '1:735764021781:ios:b73cbe6941241324c7441c',
    messagingSenderId: '735764021781',
    projectId: 'firstapp-3645c',
    storageBucket: 'firstapp-3645c.appspot.com',
    iosBundleId: 'com.example.markatemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAx4JcY3RVoHk_KC5VpBmNCMv2KHvSNqA',
    appId: '1:735764021781:ios:b73cbe6941241324c7441c',
    messagingSenderId: '735764021781',
    projectId: 'firstapp-3645c',
    storageBucket: 'firstapp-3645c.appspot.com',
    iosBundleId: 'com.example.markatemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqcpIYNXex4t6nO1rpND92ksaRdtt_8l4',
    appId: '1:735764021781:web:df2162ae41e4fdc2c7441c',
    messagingSenderId: '735764021781',
    projectId: 'firstapp-3645c',
    authDomain: 'firstapp-3645c.firebaseapp.com',
    storageBucket: 'firstapp-3645c.appspot.com',
  );
}
